In [5]:
import pandas as pd
import numpy as np

In [6]:
date_df = pd.read_csv('dim_date.csv')
maker_df = pd.read_csv('electric_vehicle_sales_by_makers.csv')
state_df = pd.read_csv('electric_vehicle_sales_by_state.csv')
date_df.head()

        date  fiscal_year quarter
0  01-Apr-21         2022      Q1
1  01-May-21         2022      Q1
2  01-Jun-21         2022      Q1
3  01-Jul-21         2022      Q2
4  01-Aug-21         2022      Q2

In [7]:
maker_df.head(90)

         date vehicle_category            maker  electric_vehicles_sold
0   01-Apr-21       2-Wheelers     OLA ELECTRIC                       0
1   01-Apr-22       2-Wheelers         OKAYA EV                       0
2   01-May-21       2-Wheelers     OLA ELECTRIC                       0
3   01-Jun-21       2-Wheelers     OLA ELECTRIC                       0
4   01-Jul-21       2-Wheelers     OLA ELECTRIC                       0
..        ...              ...              ...                     ...
85  01-Feb-23       4-Wheelers  PCA Automobiles                       0
86  01-Mar-22       4-Wheelers  PCA Automobiles                       0
87  01-Mar-22       4-Wheelers       KIA Motors                       0
88  01-Apr-21       4-Wheelers      Tata Motors                     322
89  01-Apr-21       4-Wheelers         MG Motor                     118

[90 rows x 4 columns]

In [8]:
state_df.head()

,date,state,vehicle_category,electric_vehicles_sold,total_vehicles_sold
0,01-Apr-21,Sikkim,2-Wheelers,0,398
1,01-Apr-21,Sikkim,4-Wheelers,0,361
2,01-May-21,Sikkim,2-Wheelers,0,113
3,01-May-21,Sikkim,4-Wheelers,0,98
4,01-Jun-21,Sikkim,2-Wheelers,0,229

In [9]:
date_df["date"] = pd.to_datetime(
    date_df["date"],
    format="%d-%b-%y"
)
date_df

         date  fiscal_year quarter
0  2021-04-01         2022      Q1
1  2021-05-01         2022      Q1
2  2021-06-01         2022      Q1
3  2021-07-01         2022      Q2
4  2021-08-01         2022      Q2
5  2021-09-01         2022      Q2
6  2021-10-01         2022      Q3
7  2021-11-01         2022      Q3
8  2021-12-01         2022      Q3
9  2022-01-01         2022      Q4
10 2022-02-01         2022      Q4
11 2022-03-01         2022      Q4
12 2022-04-01         2023      Q1
13 2022-05-01         2023      Q1
14 2022-06-01         2023      Q1
15 2022-07-01         2023      Q2
16 2022-08-01         2023      Q2
17 2022-09-01         2023      Q2
18 2022-10-01         2023      Q3
19 2022-11-01         2023      Q3
20 2022-12-01         2023      Q3
21 2023-01-01         2023      Q4
22 2023-02-01         2023      Q4
23 2023-03-01         2023      Q4
24 2023-04-01         2024      Q1
25 2023-05-01         2024      Q1
26 2023-06-01         2024      Q1
27 2023-07-01         2024      Q2
28 2023-08-01         2024      Q2
29 2023-09-01         2024      Q2
30 2023-10-01         2024      Q3
31 2023-11-01         2024      Q3
32 2023-12-01         2024      Q3
33 2024-01-01         2024      Q4
34 2024-02-01         2024      Q4
35 2024-03-01         2024      Q4

In [10]:
maker_df["date"] = pd.to_datetime(
    maker_df["date"],
    format="%d-%b-%y"
)
maker_df

          date vehicle_category            maker  electric_vehicles_sold
0   2021-04-01       2-Wheelers     OLA ELECTRIC                       0
1   2022-04-01       2-Wheelers         OKAYA EV                       0
2   2021-05-01       2-Wheelers     OLA ELECTRIC                       0
3   2021-06-01       2-Wheelers     OLA ELECTRIC                       0
4   2021-07-01       2-Wheelers     OLA ELECTRIC                       0
..         ...              ...              ...                     ...
811 2024-03-01       2-Wheelers           BGAUSS                    3070
812 2024-03-01       2-Wheelers  BATTRE ELECTRIC                     625
813 2024-03-01       2-Wheelers    KINETIC GREEN                    3915
814 2024-03-01       2-Wheelers           REVOLT                     585
815 2024-03-01       2-Wheelers           OTHERS                   10579

[816 rows x 4 columns]

In [11]:
state_df["date"] = pd.to_datetime(
    state_df["date"],
    format="%d-%b-%y"
)
state_df

,date,state,vehicle_category,electric_vehicles_sold,total_vehicles_sold
0,2021-04-01,Sikkim,2-Wheelers,0,398
1,2021-04-01,Sikkim,4-Wheelers,0,361
2,2021-05-01,Sikkim,2-Wheelers,0,113
3,2021-05-01,Sikkim,4-Wheelers,0,98
4,2021-06-01,Sikkim,2-Wheelers,0,229
...,...,...,...,...,...
2440,2024-03-01,Mizoram,2-Wheelers,58,1932
2441,2024-03-01,DNH and DD,2-Wheelers,25,780
2442,2024-03-01,Manipur,2-Wheelers,13,1394
2443,2024-03-01,Andaman & Nicobar Island,2-Wheelers,2,447
2444,2024-03-01,Nagaland,2-Wheelers,2,1180

In [12]:
date_df.dtypes
maker_df.dtypes
state_df.dtypes

date                      datetime64[us]
state                                str
vehicle_category                     str
electric_vehicles_sold             int64
total_vehicles_sold                int64
dtype: object

In [13]:
date_df.duplicated().sum()

np.int64(0)

In [14]:
maker_df.duplicated().sum()

np.int64(0)

In [15]:
state_df.duplicated().sum()

np.int64(0)

In [16]:
print("data table")
print(date_df.isnull().sum())
print("\nmaker table")
print(maker_df.isnull().sum())
print("\nState table")
print(state_df.isnull().sum())

data table
date           0
fiscal_year    0
quarter        0
dtype: int64

maker table
date                      0
vehicle_category          0
maker                     0
electric_vehicles_sold    0
dtype: int64

State table
date                      0
state                     0
vehicle_category          0
electric_vehicles_sold    0
total_vehicles_sold       0
dtype: int64

In [17]:
#here we check for unique categories
print(maker_df["vehicle_category"].unique())

<StringArray>
['2-Wheelers', '4-Wheelers']
Length: 2, dtype: str

In [18]:
print(state_df["vehicle_category"].unique())

<StringArray>
['2-Wheelers', '4-Wheelers']
Length: 2, dtype: str

In [19]:
print(maker_df["maker"].unique())

<StringArray>
[       'OLA ELECTRIC',            'OKAYA EV',           'BYD India',
     'PCA Automobiles',           'BMW India',    'Volvo Auto India',
          'KIA Motors',   'Mercedes -Benz AG',         'Tata Motors',
            'MG Motor', 'Mahindra & Mahindra',       'Hyundai Motor',
       'HERO ELECTRIC',             'OKINAWA',              'AMPERE',
               'ATHER',             'PURE EV',                 'TVS',
              'REVOLT',               'BAJAJ',               'BEING',
            'JITENDRA',              'OTHERS',              'BGAUSS',
     'BATTRE ELECTRIC',       'KINETIC GREEN']
Length: 26, dtype: str

In [20]:
print(state_df["state"].unique().shape[0])

35

In [21]:
print(date_df["fiscal_year"].unique())

[2022 2023 2024]

In [22]:
#Basic EDA
total_ev_sales=maker_df["electric_vehicles_sold"].sum()
print("total_ev_sales:",total_ev_sales)

total_ev_sales: 2066111

In [23]:
#sales by vehicle category
sales_by_category = maker_df.groupby("vehicle_category")["electric_vehicles_sold"].sum()
print("sales by category:",sales_by_category)

sales by category: vehicle_category
2-Wheelers    1913168
4-Wheelers     152943
Name: electric_vehicles_sold, dtype: int64

In [24]:
#Ev sales by fiscal year
maker_df = maker_df.merge(
    date_df,
    on="date",
    how="left"
)

In [25]:
yearly_ev_sales = maker_df.groupby(["fiscal_year","vehicle_category"])["electric_vehicles_sold"].sum().reset_index()
yearly_ev_sales

   fiscal_year vehicle_category  electric_vehicles_sold
0         2022       2-Wheelers                  252573
1         2022       4-Wheelers                   18577
2         2023       2-Wheelers                  727903
3         2023       4-Wheelers                   47465
4         2024       2-Wheelers                  932692
5         2024       4-Wheelers                   86901

In [26]:
yearly_ev_sales["growth_%"] = yearly_ev_sales.groupby("vehicle_category")["electric_vehicles_sold"].pct_change()*100
yearly_ev_sales

   fiscal_year vehicle_category  electric_vehicles_sold    growth_%
0         2022       2-Wheelers                  252573         NaN
1         2022       4-Wheelers                   18577         NaN
2         2023       2-Wheelers                  727903  188.195096
3         2023       4-Wheelers                   47465  155.504118
4         2024       2-Wheelers                  932692   28.134106
5         2024       4-Wheelers                   86901   83.084378

In [27]:
date_df.to_csv("dim_date_cleaned.csv", index=False)

maker_df.to_csv(
    "electric_vehicle_sales_by_makers_cleaned.csv",
    index=False
)

state_df.to_csv(
    "electric_vehicle_sales_by_state_cleaned.csv",
    index=False
)